# This is a generated file. Not intended for manual editing.
services:
  ebceys.healthchecksservice:
    build:
      context: "/home/ebceys/projects/EBCEYS.HealthChecksService/src"
      dockerfile: "EBCEYS.HealthChecksService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ebceyshealthchecksservice:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/home/ebceys/projects/EBCEYS.HealthChecksService/src/EBCEYS.HealthChecksService:/app:rw"
    - "/home/ebceys/projects/EBCEYS.HealthChecksService/src:/src:rw"
    - "/home/ebceys/.nuget/packages:/root/.nuget/packages"
    - "/home/ebceys/.local/share/JetBrains/RiderRemoteDebugger/2025.2.2/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/634/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ebceys/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_21_13_00_17:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
